version: "3.9"

services:
  cpp_dev:
    container_name: cpp-dev-container
    build:
      context: .
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
    user: "devuser"
